FROM node:18-alpine
RUN npm install -g json-server
WORKDIR /app
COPY package.json package-lock.json ./
COPY . .
CMD ["json-server", "--watch", "db.json", "--port", "8082", "--no-cors", "--host", "0.0.0.0"]
