version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    command: ["nginx", "-g", "daemon off;"]

  json-server:
    image: codfish/json-server:0.17.3
    command: npm run dev
    ports:
      - "8082:80"
    volumes: 
      - ./db.json:/app/db.json:delegated
    depends_on:
      - web

