version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    command: ["nginx", "-g", "daemon off;"]

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.json-server
    ports:
      - "8082:8082"
    volumes: 
      - ./db.json:/app/db.json
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
